Registration
mattydono/operation-bark pull request #1
Opened 2019-03-24 13:12 UTC by mattydono

Hi,

Sorry about the size of this PR but I had started working on parts before you showed me appropriate sizing. Going ahead I'll make sure to keep PR's relevant to the importance of the feature or fix.

- Added/Implemented Redux
- Added emotion

Thanks,

Matt

2019-03-25 15:12 UTC, Sharakai requested changes
Hopefully you can see the review now!

2019-03-25 15:12 UTC, Sharakai commented on package.json
> +    "@types/react-redux": "^7.0.5",
`@types` packages should be in `devDependencies` - they are only used for working on, and building, the project, and not in the runtime code at all.

2019-03-25 15:12 UTC, Sharakai commented on src/App.tsx
> +  private store: Store<AppState> = configureStore();
We need to be more careful doing this, as it is transpiled to be in the `constructor`, which can be invoked multiple times in concurrent rendering (next version of React).
Doing it here also blocks rendering until the store is fully set up.

2019-03-25 15:12 UTC, Sharakai commented on src/Registration/Registration.tsx
> +        type: string
This should likely be stricter typed, either as an enum or a string literal union.

2019-03-25 15:12 UTC, Sharakai commented on src/Registration/Registration.tsx
> +    private onTypeChange = (event: React.ChangeEvent<HTMLSelectElement>) => {
You can nicer type this as...

```ts
private onTypeChange: React.ChangeEventHandler<HTMLSelectElement> = event => { ...
```

Same for the other handlers below.

2019-03-25 15:12 UTC, Sharakai commented on src/Registration/redux/userReducer.tsx
> +    users: User[]
I would re-consider this being an array, and using a dictionary (object) instead, with an auto-generated uuid key - also include that ID as part of the User type.

2019-03-25 15:12 UTC, Sharakai commented on tslint.json
> +    "no-console": false,
This shouldn't be here. `no-console` is a very good lint rule.
Same with the `class-name` rule.

These would have stopped it from compiling before, but I've changed the `defaultSeverity` to "warning" so it no longer will.

2019-03-25 15:22 UTC, mattydono commented on src/Registration/Registration.tsx
> +    private onTypeChange = (event: React.ChangeEvent<HTMLSelectElement>) => {
okay so this is essentially stating 

What we're listening for: the type of event = the event itself => {

?

2019-03-25 15:26 UTC, mattydono commented on src/Registration/redux/userReducer.tsx
> +    users: User[]
would I need an ID for a user as their email addresses provided will be unique identifiers?

2019-03-26 08:14 UTC, Sharakai commented on src/Registration/User.ts
> +export type UserType = string;
You don't need to do all these types - It's very verbose, and doesn't add anything.
Just change the below `User` type to have them as strings...

```ts
export type User = {
  firstName: string;
  surname: string;
  email: string;
  type: UserType; (the enum)
}
```

2019-03-26 08:14 UTC, Sharakai commented on src/Registration/redux/userReducer.tsx
> +export function usersReducer(
Why the decision not to use `redux-actions`' `handleActions`, seeing as you're already using `createAction` from the same library?

2019-03-27 11:10 UTC, Sharakai commented on src/Registration/Registration.tsx
> +    private onTypeChange = (event: React.ChangeEvent<HTMLSelectElement>) => {
It's retyping `onTypeChange` as a function which takes an event and returns nothing (`void`).
Previously, you only had the `event` typed, which doesn't strictly-type the return type of `void`

2019-03-27 11:11 UTC, Sharakai commented on src/Registration/redux/userReducer.tsx
> +    users: User[]
In that case, you could use the `email` as the object key.
`Record<Email, User>;`

2019-04-01 22:06 UTC, closed without merging